openapi: 3.0.1
info:
  title: Eclipse Dataspace Connector Registration Service
  version: 0.0.1
paths:
  /registry/participant:
    post:
      description: Asynchronously request to add a dataspace participant.
      operationId: addParticipant
      parameters:
      - in: header
        name: Did
        schema:
          type: string
      responses:
        "204":
          description: No content
      tags:
      - Registry
  /registry/participants:
    get:
      description: Gets all dataspace participants.
      operationId: listParticipants
      responses:
        default:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Participant'
          description: Dataspace participants.
      tags:
      - Registry
components:
  schemas:
    Participant:
      type: object
      properties:
        did:
          type: string
        status:
          type: string
          enum:
          - ONBOARDING_INITIATED
          - AUTHORIZING
          - AUTHORIZED
          - DENIED
